**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [1]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
transposed_array = np.transpose(array)
print("Original Array:")
print(array)
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[73 47 56]
 [ 8 12 59]
 [15 31 85]]

Transposed Array:
[[73  8 15]
 [47 12 31]
 [56 59 85]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [2]:
import numpy as np
array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_1d.reshape(5, 2)
print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [3]:
import numpy as np
array_4x4 = np.random.rand(4, 4)
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Zero Border:")
print(array_with_border)

Original 4x4 Array:
[[0.84726949 0.56056465 0.93332467 0.62915941]
 [0.54536802 0.92412021 0.42466095 0.71712906]
 [0.71655792 0.80121142 0.52517814 0.4829732 ]
 [0.87595794 0.75711716 0.01849683 0.14718864]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.84726949 0.56056465 0.93332467 0.62915941 0.        ]
 [0.         0.54536802 0.92412021 0.42466095 0.71712906 0.        ]
 [0.         0.71655792 0.80121142 0.52517814 0.4829732  0.        ]
 [0.         0.87595794 0.75711716 0.01849683 0.14718864 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5**

In [4]:
import numpy as np
array_integers = np.arange(10, 61, 5)
print(array_integers)

[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [5]:
import numpy as np
array_strings = np.array(['python', 'numpy', 'pandas'])
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)
print("Original Array:")
print(array_strings)
print("\nUppercase Array:")
print(uppercase_array)
print("\nLowercase Array:")
print(lowercase_array)
print("\nTitlecase Array:")
print(titlecase_array)
print("\nCapitalize Array:")
print(capitalize_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']

Capitalize Array:
['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [6]:
import numpy as np
array_words = np.array(['hello', 'world', 'numpy', 'python'])
spaced_array = np.char.join(' ', array_words)
print("Original Array:")
print(array_words)
print("\nArray with Spaces:")
print(spaced_array)

Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [7]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
division_result = array1 / array2
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition_result)
print("\nElement-wise Subtraction:")
print(subtraction_result)
print("\nElement-wise Multiplication:")
print(multiplication_result)
print("\nElement-wise Division:")
print(division_result)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [8]:
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
identity_matrix, diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

In [9]:
import numpy as np
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return np.True_
random_integers = np.random.randint(0, 1001, size=100)
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(prime_numbers)

Random Integers:
[370 204 683 855 805 936 378 274 671 998 836 525 452 819 862 554 718 647
 393 469 513 102 409 875 195 117   4 609 396  63 637 436 506 210 945 683
 632 120 355 437 712 748 458 760 620 472 388 722 909 797 636 774 855 493
  64 227 473 286 313 811 147 269 284 896 360 501 987 983 974 344 319  62
 624 574  71 679 904 603 294 756 932 902 433 911  49 331 236 208 610  87
 738 471 118  64 164 502   6 303 495 800]

Prime Numbers:
[683, 647, 409, 683, 797, 227, 313, 811, 269, 983, 71, 433, 911, 331]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [12]:
import numpy as np
daily_temperatures = np.random.uniform(low=15.0, high=35.0, size=30)
weekly_temperatures = np.array_split(daily_temperatures, 4)
weekly_averages = [np.mean(week) for week in weekly_temperatures]
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[25.25885443 17.69669672 19.87532371 28.19857238 32.80514552 22.5257735
 29.93233664 23.91573553 18.44102915 17.99065034 28.86370491 20.17975289
 33.80193658 15.76810805 28.13621458 20.26955441 32.94950833 17.46932944
 29.30578676 29.60252258 21.03434262 23.93912846 15.715273   20.28627716
 29.02678499 22.50334811 16.38151985 33.71609429 21.60429469 21.55886505]

Weekly Averages:
[25.026054802953354, 22.93136886338164, 24.28798445632553, 23.582454877807585]
